@startuml(id=jianmu-container)
title 建木自动化集成平台 - Containers
caption 建木容器图

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052E56
}
skinparam rectangle<<13>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<3>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<8>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<9>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
rectangle "==用户\n<size:10>[Person]</size>\n\n泛指用户" <<1>> as 1
package "建木自动化集成平台\n[Software System]" {
  rectangle "==docker-worker\n<size:10>[Container]</size>\n\n容器化执行环境" <<9>> as 9
  rectangle "==shell-worker\n<size:10>[Container]</size>\n\n非容器化执行环境" <<13>> as 13
  rectangle "==主服务\n<size:10>[Container]</size>\n\n主服务" <<3>> as 3
  rectangle "==数据库\n<size:10>[Container]</size>\n\nMysql 8.0" <<8>> as 8
}
9 .[#707070].> 3 : "返回执行结果"
13 .[#707070].> 3 : "返回执行结果"
3 .[#707070].> 9 : "下发任务执行"
3 .[#707070].> 13 : "下发任务执行"
3 .[#707070].> 8 : "Reads from and writes to\n<size:8>[JDBC/SSL]</size>"
1 .[#707070].> 3 : "启动流程或任务"
@enduml