@startuml(id=DevelopmentDeployment)
title 建木自动化集成平台 - Deployment - dev

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
top to bottom direction
skinparam rectangle<<55>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam node<<57>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
skinparam node<<47>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
skinparam node<<58>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
skinparam rectangle<<48>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam rectangle<<59>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam node<<49>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
skinparam node<<50>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
skinparam rectangle<<51>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
skinparam node<<53>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
skinparam node<<54>> {
  BackgroundColor #ffffff
  FontColor #000000
  BorderColor #000000
  roundCorner 20
}
node "Docker Container - Database Server\n[Deployment Node: Docker]" <<53>> as 53 {
  node "Database Server\n[Deployment Node: Mysql 8.0]" <<54>> as 54 {
    rectangle "==数据库\n<size:10>[Container]</size>\n\nMysql 8.0" <<55>> as 55
  }
}
node "Docker Container - Web Server\n[Deployment Node: Docker]" <<49>> as 49 {
  node "Spring boot\n[Deployment Node: Spring boot 2.4.4]" <<50>> as 50 {
    rectangle "==主服务\n<size:10>[Container]</size>\n\n主服务" <<51>> as 51
  }
}
node "Docker Container - Worker Server\n[Deployment Node: Docker]" <<57>> as 57 {
  node "Worker Server\n[Deployment Node: Golang]" <<58>> as 58 {
    rectangle "==docker-worker\n<size:10>[Container]</size>\n\n容器化执行环境" <<59>> as 59
  }
}
node "Web Browser\n[Deployment Node: Chrome, Firefox, Safari, or Edge]" <<47>> as 47 {
  rectangle "==SPA单页面应用\n<size:10>[Container: TypeScript and Vue 3.0]</size>\n\nProvides all of the Jianmu functionality to customers via their web browser." <<48>> as 48
}
48 .[#707070].> 51 : "启动流程或任务\n<size:8>[Rest API]</size>"
59 .[#707070].> 51 : "返回执行结果\n<size:8>[grpc]</size>"
51 .[#707070].> 59 : "下发任务执行\n<size:8>[grpc]</size>"
51 .[#707070].> 55 : "读写数据\n<size:8>[JDBC/SSL]</size>"
@enduml