@startuml(id=worker-component)
title 建木自动化集成平台 - docker-worker - Components
caption 执行器组件图

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
left to right direction
skinparam rectangle<<11>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5D82A8
  roundCorner 20
}
skinparam rectangle<<12>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5D82A8
  roundCorner 20
}
skinparam rectangle<<13>> {
  BackgroundColor #85bbf0
  FontColor #000000
  BorderColor #5D82A8
  roundCorner 20
}
skinparam rectangle<<4>> {
  BackgroundColor #438dd5
  FontColor #ffffff
  BorderColor #2E6295
  roundCorner 20
}
rectangle "==主服务\n<size:10>[Container]</size>\n\n主服务" <<4>> as 4
package "docker-worker\n[Container]" {
  rectangle "==Ansible执行\n<size:10>[Component]</size>\n\n任务运行容器" <<13>> as 13
  rectangle "==daemon\n<size:10>[Component]</size>\n\nworker守护容器" <<11>> as 11
  rectangle "==代码编译\n<size:10>[Component]</size>\n\n任务运行容器" <<12>> as 12
}
11 .[#707070].> 13 : "启动容器"
11 .[#707070].> 4 : "返回执行结果"
11 .[#707070].> 12 : "启动容器"
4 .[#707070].> 11 : "下发任务执行"
@enduml